name: Java CI with Maven
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      run: |
        # Check out the repository
        git clone ${{ github.repository }} 
                  ${{ github.workspace }}
    - name: Set up JDK 17
      run: |
        # Set up JDK 17
        sudo apt-get install -y openjdk-17-jdk
    - name: Build with Maven
      run: |
        # Build with Maven
        mvn -B package --file pom.xml
