# This workflow will trigger on every push or pull request to the main branch. It will run on the ubuntu-latest environment and perform the following steps:
# 1. Check out the code from the repository.
# 2. Set up Java 17 on the runner.
# 3. Build the project using Maven.
# 4. Run the unit tests using Maven.
# 5. Cache the Maven repository to speed up builds.
# 6. Generate an HTML report of the test results using the JUnit Test Report action.


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-swing-app:latest
      
      - name: Run tests
        run: |
          docker run -it --rm \
            -v "$(pwd)":/app \
            -e DISPLAY=$DISPLAY \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            my-swing-app mvn test
